import MainLayout from "@/layouts/main-layout";
import ThemeRegistry from "@/libs/joy-ui/theme-registry";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import 'styles/global.scss'

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${openSans.variable}`}>
        <ThemeRegistry options={{ key: 'joy' }}>
          <MainLayout>
            {children}
          </MainLayout>
        </ThemeRegistry>
      </body>
    </html >
  );
}
